"""Inspectable source extract of the decisive same-seed prefix comparisons (review fix F2).

Standard library only; executes no model, replay or checkpoint. Two modes:

  extract  (needs the pinned Windows originals)
      checks the SHA-256 and size of the six source streams against their pins BEFORE reading,
      copies the selected JSONL lines BYTE-FOR-BYTE (original line terminator included) into
      ``prefix_source_extract/``, re-checks the pins AFTER, writes ``index.json`` (source path,
      pinned and observed hash, 1-based line number, record key, per-line SHA-256 and length,
      output-file hashes) and builds ``comparison_report.json``;
  verify   (needs only the committed extract)
      re-hashes every extracted line and output file against ``index.json`` and rebuilds
      ``comparison_report.json``, requiring byte identity.

Selected records, from BOTH runs:
  * the pre-update evaluation episode with seed 2000448 (the declared first divergence);
  * the eight training episodes of iteration 0;
  * the iteration-1 training episode with seed 3000008 (the first detected training output
    difference);
  * the iteration-0 train record and the 17 iteration-0 credit rows.

The report uses the EXECUTED comparator's own normalization and classifier
(``compare_prefix.normalize`` / ``first_difference`` / ``classify_episode`` /
``_WAKE_INPUT_FIELDS``) unchanged, and lists, for every pair, ALL differing leaves (not only the
first), their exact values and, separately, the leaves that differ only before normalization.

LIMIT, stated in the report: an episode outcome record carries SELECTED wake fields (the listed
actor-input summaries and the policy outputs), not a serialized GraphObservation -- no complete
task-feature matrix, agent-feature matrix or edge tensor. Equal recorded summaries therefore do
not prove equal full actor inputs, and a float32 output difference alone does not show when or
why parameters diverged. Missing observations are NOT regenerated by replay.

Usage:
  python extract_prefix_source.py extract <package> <new run dir> <original run dir>
  python extract_prefix_source.py verify <package>
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import compare_prefix as C  # noqa: E402  (the executed comparator, unchanged)

OUT = "prefix_source_extract"
# Pins: the new run's from this package's artifact_sha256.txt; the original's from the PR #79
# package's artifact_sha256.txt (research_evidence/generalized_v2/actor_mission_slack_dev_r1/).
PINS = {
    "new": {
        "episode_outcomes.jsonl": ("3af8bec228116d3597dc0853b918d7ed81d4df81b69dd61ee36699b2c2816379", 29017283),
        "train_records.jsonl": ("42ab2457cdab81cca49dd8d2ada847f48e57cf00efbb9e7cfb0adf07bf99d779", 274926),
        "train_credit_diagnostics.jsonl": ("a687b2b0bd451572d8b5201757ae41b7515f5a7c5639de4fdd9ffac1ba9b09ed", 3109486),
    },
    "original": {
        "episode_outcomes.jsonl": ("d03c43c8463a1c102a35cf81b2cbb41ed62ba1e7e4b7394b40e2df006c28cfbe", 106129593),
        "train_records.jsonl": ("5ba09db3ee1c8b46256016cd5a733601ba7230b9423c1bdc36740bb66529a157", 1027772),
        "train_credit_diagnostics.jsonl": ("3db9ca1e155ed5d82bde1a4fec4f9f46b3e0921f8c41fc4b5ad2ae895661bbdc", 12003603),
    },
}


def _sha_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _sha_file(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _selected(stream: str, rec: dict) -> bool:
    if stream == "episode_outcomes.jsonl":
        if rec.get("phase") == "pre_update" and rec.get("seed") == 2000448:
            return True
        if rec.get("phase") == "train" and rec.get("iteration") == 0:
            return True
        return rec.get("phase") == "train" and rec.get("iteration") == 1 \
            and rec.get("seed") == 3000008
    return rec.get("iteration") == 0


def _key(stream: str, rec: dict) -> list:
    if stream == "episode_outcomes.jsonl":
        return list(C._outcome_key(rec))
    if stream == "train_credit_diagnostics.jsonl":
        return [rec["iteration"], rec["batch_transition_ordinal"]]
    return [rec["iteration"]]


def _check_pins(dirs: dict) -> list:
    rows = []
    for run, streams in PINS.items():
        for name, (sha, size) in streams.items():
            p = dirs[run] / name
            got = (_sha_file(p), p.stat().st_size)
            rows.append({"run": run, "stream": name, "path": str(p), "pinned_sha256": sha,
                         "pinned_bytes": size, "sha256": got[0], "bytes": got[1],
                         "match": got == (sha, size)})
    return rows


def extract(pkg: Path, new_dir: Path, orig_dir: Path) -> None:
    dirs = {"new": new_dir, "original": orig_dir}
    before = _check_pins(dirs)
    if not all(r["match"] for r in before):
        raise SystemExit("pinned source mismatch BEFORE extraction: %s" % before)
    out = pkg / OUT
    out.mkdir(parents=True, exist_ok=True)
    index = {"record": "prefix_source_extract_index", "record_version": 1, "files": []}
    for run in ("new", "original"):
        for name in PINS[run]:
            src = dirs[run] / name
            lines_out, sel = [], []
            with open(src, "rb") as fh:
                for n, raw in enumerate(fh, start=1):
                    rec = json.loads(raw)
                    if _selected(name, rec):
                        lines_out.append(raw)
                        sel.append({"line_number": n, "key": _key(name, rec),
                                    "line_sha256": _sha_bytes(raw), "line_bytes": len(raw)})
            fname = "%s__%s" % (run, name)
            data = b"".join(lines_out)
            (out / fname).write_bytes(data)
            index["files"].append({"file": fname, "run": run, "source_stream": name,
                                   "source_path": str(src),
                                   "source_sha256": PINS[run][name][0],
                                   "source_bytes": PINS[run][name][1],
                                   "n_lines": len(sel), "sha256": _sha_bytes(data),
                                   "bytes": len(data), "lines": sel})
    after = _check_pins(dirs)
    if not all(r["match"] for r in after):
        raise SystemExit("pinned source mismatch AFTER extraction: %s" % after)
    index["pins_checked_before"] = before
    index["pins_checked_after"] = after
    (out / "index.json").write_bytes(
        (json.dumps(index, indent=1, sort_keys=True) + "\n").encode("utf-8"))
    (out / "comparison_report.json").write_bytes(build_report(out))


def _all_differences(a, b, where=""):
    """Every differing leaf (depth first), with values and the absolute difference."""
    out = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in list(a) + [k for k in b if k not in a]:
            if k not in a or k not in b:
                out.append({"path": where + "/" + str(k), "new": a.get(k, "<absent>"),
                            "original": b.get(k, "<absent>")})
            else:
                out.extend(_all_differences(a[k], b[k], where + "/" + str(k)))
        return out
    if isinstance(a, list) and isinstance(b, list):
        for i, (x, y) in enumerate(zip(a, b)):
            out.extend(_all_differences(x, y, "%s[%d]" % (where, i)))
        if len(a) != len(b):
            out.append({"path": where + "#len", "new": len(a), "original": len(b)})
        return out
    if a != b or type(a) is not type(b) and not (
            isinstance(a, (int, float)) and isinstance(b, (int, float))):
        d = {"path": where, "new": a, "original": b}
        if isinstance(a, (int, float)) and isinstance(b, (int, float)) \
                and not isinstance(a, bool) and not isinstance(b, bool):
            d["abs_diff"] = abs(float(a) - float(b))
        out.append(d)
    return out


def _load(out: Path, name: str) -> list:
    return [json.loads(x) for x in (out / name).read_bytes().splitlines() if x.strip()]


def build_report(out: Path) -> bytes:
    rep = {
        "record": "prefix_source_comparison", "record_version": 1,
        "comparator": "scripts/compare_prefix.py (the executed comparator), unchanged",
        "tolerance": 0.0,
        "wake_input_fields_compared": list(C._WAKE_INPUT_FIELDS),
        "normalization": {
            "time_key_substrings_dropped": list(C._TIME_KEYS),
            "path_keys_dropped": sorted(C._PATH_KEYS),
            "uuid_values_substrings_and_dict_keys": "replaced by <uuid> / <uuid#ordinal>",
            "absolute_windows_paths_inside_strings": "replaced by <path>",
        },
        "limit": ("An outcome record carries selected wake fields -- the listed actor-input "
                  "summaries and the policy outputs -- not a serialized GraphObservation (no "
                  "complete task-feature matrix, agent-feature matrix or edge tensor). Equal "
                  "recorded summaries do not prove equal full actor inputs, and a float32 "
                  "output difference alone does not show when or why parameters diverged. "
                  "Missing observations are not regenerated by replay."),
        "pairs": [],
    }
    new_o = {tuple(C._outcome_key(r)): r for r in _load(out, "new__episode_outcomes.jsonl")}
    org_o = {tuple(C._outcome_key(r)): r for r in _load(out, "original__episode_outcomes.jsonl")}
    wake_keys = set()
    for key in sorted(new_o, key=lambda k: (str(k[0]), k[1] if k[1] is not None else -1,
                                            k[2], k[5])):
        a, b = new_o[key], org_o.get(key)
        entry = {"kind": "episode_outcome", "key": list(key), "present_in_original": b is not None}
        if b is not None:
            na, nb = C.normalize(a), C.normalize(b)
            diffs = _all_differences(na, nb)
            raw_paths = {d["path"] for d in _all_differences(a, b)}
            norm_paths = {d["path"] for d in diffs}
            for w in a.get("wake_decisions") or []:
                wake_keys |= set(w)
            per_wake = []
            for i, (wa, wb) in enumerate(zip(na.get("wake_decisions") or [],
                                             nb.get("wake_decisions") or [])):
                d = _all_differences(wa, wb)
                per_wake.append({
                    "wake_index": i, "tick_new": wa.get("tick"), "tick_original": wb.get("tick"),
                    "wake_kind": wa.get("wake_kind"),
                    "input_fields_differing": sorted(
                        f for f in C._WAKE_INPUT_FIELDS
                        if C.first_difference(wa.get(f), wb.get(f)) is not None),
                    "n_differing_leaves": len(d),
                    "max_abs_diff": max((x.get("abs_diff", 0.0) for x in d), default=0.0)})
            entry.update({
                "normalized_identical": not diffs,
                "classification": (None if not diffs else C.classify_episode(a, b)),
                "n_wakes": [len(a.get("wake_decisions") or []), len(b.get("wake_decisions") or [])],
                "per_wake": per_wake,
                "n_differing_leaves": len(diffs),
                "max_abs_diff_all_numeric_leaves": max((d.get("abs_diff", 0.0) for d in diffs),
                                                       default=0.0),
                "all_differences": diffs,
                "raw_only_difference_paths": sorted(raw_paths - norm_paths),
            })
        rep["pairs"].append(entry)
    rep["recorded_wake_fields"] = sorted(wake_keys)
    for stream, kind, keyf in (("train_records.jsonl", "train_record", lambda r: (r["iteration"],)),
                               ("train_credit_diagnostics.jsonl", "credit_row",
                                lambda r: (r["iteration"], r["batch_transition_ordinal"]))):
        na = {keyf(r): r for r in _load(out, "new__" + stream)}
        nb = {keyf(r): r for r in _load(out, "original__" + stream)}
        for k in sorted(na):
            diffs = _all_differences(C.normalize(na[k]), C.normalize(nb[k])) if k in nb else None
            rep["pairs"].append({"kind": kind, "key": list(k), "present_in_original": k in nb,
                                 "normalized_identical": diffs == [],
                                 "all_differences": diffs})
    eps = [p for p in rep["pairs"] if p["kind"] == "episode_outcome"]
    rep["summary"] = {
        "episode_pairs": len(eps),
        "episode_pairs_identical": sum(1 for p in eps if p.get("normalized_identical")),
        "iteration0_train_episodes_identical": sum(
            1 for p in eps if p["key"][0] == "train" and p["key"][1] == 0
            and p.get("normalized_identical")),
        "iteration0_train_record_identical": all(
            p["normalized_identical"] for p in rep["pairs"] if p["kind"] == "train_record"),
        "iteration0_credit_rows": sum(1 for p in rep["pairs"] if p["kind"] == "credit_row"),
        "iteration0_credit_rows_identical": sum(
            1 for p in rep["pairs"] if p["kind"] == "credit_row" and p["normalized_identical"]),
    }
    return (json.dumps(rep, indent=1, sort_keys=True, default=str) + "\n").encode("utf-8")


def verify(pkg: Path) -> int:
    out = pkg / OUT
    index = json.loads((out / "index.json").read_text(encoding="utf-8"))
    bad = []
    for f in index["files"]:
        data = (out / f["file"]).read_bytes()
        if _sha_bytes(data) != f["sha256"] or len(data) != f["bytes"]:
            bad.append(f["file"])
        lines = data.splitlines(keepends=True)
        if [_sha_bytes(x) for x in lines] != [s["line_sha256"] for s in f["lines"]]:
            bad.append(f["file"] + ":lines")
    if build_report(out) != (out / "comparison_report.json").read_bytes():
        bad.append("comparison_report.json")
    print("VERIFY", "PASS" if not bad else "FAIL %s" % bad)
    return 0 if not bad else 1


def main() -> int:
    mode, pkg = sys.argv[1], Path(sys.argv[2])
    if mode == "extract":
        extract(pkg, Path(sys.argv[3]), Path(sys.argv[4]))
        return verify(pkg)
    if mode == "verify":
        return verify(pkg)
    raise SystemExit("mode must be extract or verify")


if __name__ == "__main__":
    sys.exit(main())
